version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgreSQL
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample_curd
    volumes:
      - ./_postgreSQL:/var/lib/postgresql/data
    ports:
      - "5432:5432"
