@host = http://localhost:3000/posts

###

GET {{host}}

### Create new post
// make sure to put the key as string!

POST {{host}}
Content-Type: application/json

{
  "Title": "My Test Post",
  "Body": "Hello, World!\nWelcome to my second post!"
}

### Get all posts

GET {{host}}

### Get post by id

GET  {{host}}/1

### Get post by wrong id

GET  {{host}}/123123

### Update post

PUT  {{host}}/1
Content-Type: application/json

{
  "title": "My new title",
  "body": "My new content!"
}

### Update not found post

PUT  {{host}}/11231
Content-Type: application/json

{
  "title": "My new title",
  "body": "My new content!"
}

### Delete a post with id

DELETE {{host}}/1

### Delete not found post id

DELETE {{host}}/123123