@host=http://localhost:3000/users

### Register new User

POST {{host}}/register
Accept: application/json
Content-Type: application/json

{
  "Email": "contact@codechovui.dev",
  "Password": "password@123"
}

### Login with user

POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "Email": "contact@codechovui.dev",
  "Password": "password@123"
}

### Login with wrong email

POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "Email": "contact@codechovui.dev2",
  "Password": "password@123"
}

### Login with wrong password

POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "Email": "contact@codechovui.dev",
  "Password": "password@1234"
}

### Validate Token
GET {{host}}/validate
Accept: application/json
Authorization: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbnRhY3RAY29kZWNob3Z1aS5kZXYiLCJleHBpcmVzIjoxNzAyMTM5MDk2fQ.-oys2rdClAm-QZuZNSGU7mn0CCtTOXo7UN1EV7n388ARELeMBv1HtBOk6sPWZW4CwghBcHiqmCoN-IBLbTSoTg"